<?php
return array(
	//'配置项'=>'配置值'
	'DB_TYPE'=>'mysql',
    'DB_HOST'=>'localhost',
    'DB_NAME'=>'uniqlo',
    'DB_USER'=>'root',
    'DB_PWD'=>'root',
    'DB_PORT'=>'3306',
    'DB_PREFIX'=>'u_',
	'DATA_CACHE_TIME'=>600,
	//'TAOAPIKEY'=>'21681612',
	'URL_CASE_INSENSITIVE'=>true,
	'TAOAPIKEY'=>'21660143',
	'TAOSECRET'=>'d7c0a4eee53d638546c816a91c4e0244',
	'TAOCAABACK'=>'http://phoneicolor.networking.io/uniqlo/mini.php/Index/callback',
	'UNIQLOURL'=>'http://localhost:81/U2/',
    'NEWSRORE'=>'sdgdg',
);
?>